spring:
  application:
    name: pharma.pa
  profiles:
    active: local
---
spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/desarrollo
    username: postgres
    password: 1041971977
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none
